package com.bulhakov.services;

import com.bulhakov.model.File;
import com.bulhakov.model.User;
import com.bulhakov.repository.FileRepository;
import com.bulhakov.repository.UserRepository;
import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

@Service
public class FileService {

    private final UserRepository userRepository;
    private final FileRepository fileRepository;

    @Autowired
    public FileService(UserRepository userRepository, FileRepository fileRepository) {
        this.userRepository = userRepository;
        this.fileRepository = fileRepository;
    }

    @Transactional
    public File storeFile(Long externalUserId, String filename, String externalFileId) {
        User user = getUserByExternalId(externalUserId);

        // Check if a file with this name already exists for the user to prevent duplicates
        Optional<File> existingFile = fileRepository.findByUserIdAndFileName(user.getId(), filename);
        if (existingFile.isPresent()) {
            File fileToUpdate = existingFile.get();
            File updatedFile = new File(
                    fileToUpdate.getId(), // Keep existing ID
                    user.getId(),
                    filename,
                    externalFileId, // Update external_file_id
                    Instant.now() // Update upload_date to current time
            );
            return fileRepository.save(updatedFile);
        } else {
            //TODO check if external file id isn't duplicated

            // Create a new File entity
            // Note: id is generated by DB, so we pass null for new entities
            File newFile = new File(
                    null, // Let JPA generate the ID
                    user.getId(),
                    filename,
                    externalFileId,
                    Instant.now() // Set upload date
            );
            return fileRepository.save(newFile);
        }
    }

    public List<File> getFilesForUser(String userId) {
        return fileRepository.findByUserId(userId);
    }

    public Optional<File> getFileForUser(Long externalUserId, String filename) {
        User user = getUserByExternalId(externalUserId);
        return fileRepository.findByUserIdAndFileName(user.getId(), filename);
    }

    @Transactional
    public void renameFile(Long externalUserId, String existingFileName, String newFileName) {
        User user = getUserByExternalId(externalUserId);

        // Find the file to rename
        File fileToRename = fileRepository.findByUserIdAndFileName(user.getId(), existingFileName)
                .orElseThrow(() -> new IllegalArgumentException("File '" + existingFileName + "' does not exist for user with external ID: " + externalUserId));

        // Check if a file with the new name already exists for the same user
        if (fileRepository.findByUserIdAndFileName(user.getId(), newFileName).isPresent()) {
            throw new IllegalArgumentException("A file with name '" + newFileName + "' already exists for user with external ID: " + externalUserId);
        }

        // Create a new File instance with the updated filename (records are immutable)
        File updatedFile = new File(
                fileToRename.getId(),
                user.getId(),
                newFileName, // The new filename
                fileToRename.getExternalFileId(),
                fileToRename.getUploadDate()
        );

        fileRepository.save(updatedFile);
    }

    @Transactional
    public void deleteFile(Long externalUserId, String filename) {
        User user = getUserByExternalId(externalUserId);

        // Find the file to delete
        File fileToDelete = fileRepository.findByUserIdAndFileName(user.getId(), filename)
                .orElseThrow(() -> new IllegalArgumentException("File '" + filename + "' does not exist for user with external ID: " + externalUserId));

        fileRepository.delete(fileToDelete);
    }

    private User getUserByExternalId(Long externalUserId) {
        return userRepository.findByExternalId(externalUserId)
                .orElseThrow(() -> new EntityNotFoundException("User not found with external ID: " + externalUserId));
    }
}