server:
    port: 5000

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yml
        enabled: true

telegram-bot:
    bot-name: ${ATHLON_BOT_NAME}
    bot-token: ${ATHLON_BOT_TOKEN}

athlon-setup:
    temporary-file-download-directory: '/temp/input'
    temporary-file-convertion-directory: '/temp/output'
    max-file-size-bytes: 104857600
    pool-size: 2